spring.application.name=rabbit-store-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/rabbit_store
spring.datasource.username=postgres
spring.datasource.password=ando14960

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true